### ISSUE TITLE
Add hold functionality for incoming and outgoing calls

### ISSUE THREAD

**Issue by 9mido** [TwilioDevEd/voice-javascript-sdk-quickstart-python#7]
Hold functionality is not part of the javascript SDK. 

Mute functionality helps in certain situations, but it leaves the other party wondering if you are still on the line. If you leave the other party on mute too long, they will think you hung up on them and they will most likely hang up on you if they don't hear anything.

Adding hold music to let the other party know you are still on the line with them is useful when you have to be away from the phone for longer periods of time. 

Another scenario would be to put a current call on hold and then accept another incoming call that comes in at the same time as the current call is in progress.

**Comment by bld010** [comment]
Hi! Since this is repo is just about the Quickstart application, you can give this feedback to the SDK engineering team at the [JS SDK repository](https://github.com/twilio/twilio-voice.js). 

Here's a [Stack Overflow](https://stackoverflow.com/questions/19345222/place-a-twilio-call-on-hold-and-retrieve-it-later) question about this that should point you in the right direction!

**Comment by 9mido** [comment]
Ok I made an issue there. It may be a while for me to try to figure out how to implement the stackoverflow method though.

**Comment by bld010** [comment]
@9mido  I'll close this issue, but if you have questions about your project/need help with that Stack Overflow implementation, you can push it up to a GitHub repo and I can help you out there.
